version: "3.8"

services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    cap_add:
      - sys_nice
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_DB_USER}
      MYSQL_PASSWORD: ${MYSQL_DB_PASS}
      LANG: ${MYSQL_LANG}
    command:
      - mysqld
      - --character-set-server=${MYSQL_CHARACTER_SET}
      - --collation-server=${MYSQL_COLLATION}
      - --init-connect=SET NAMES ${MYSQL_CHARACTER_SET} COLLATE ${MYSQL_COLLATION};
    volumes:
      - ./db_init_mysql:/docker-entrypoint-initdb.d
      - ./local_dir/mysql_data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      backend:
        aliases:
          - ${MYSQL_HOST_ALIAS}

  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASS}
      LANG: ${POSTGRES_LANG}
      POSTGRES_INITDB_ARGS: "--encoding=${POSTGRES_ENCODING} --lc-collate=${POSTGRES_COLLATION} --lc-ctype=${POSTGRES_CTYPE}"
    volumes:
    - ./db_init_postgres:/docker-entrypoint-initdb.d
    - ./local_dir/postgres_data:/var/lib/postgresql/data
    - ./db_init_postgres/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      backend:
        aliases:
          - ${POSTGRES_HOST_ALIAS}

  sqlserver:
    image: mcr.microsoft.com/mssql/server:${MSSQL_VERSION}
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PID: "Express"
      LANG: ${MSSQL_LANG}
    volumes:
      - ./db_init_sqlserver:/docker-entrypoint-initdb.d
      - ./local_dir/sqlserver_data:/var/opt/mssql
    ports:
      - "${MSSQL_PORT}:1433"
    networks:
      backend:
        aliases:
          - ${MSSQL_HOST_ALIAS}

networks:
  backend:
    external: true
    name: ${DOCKER_EXTERNAL_NETWORK_NAME}
